### ISSUE TITLE
BLSTM第一层的输入

### ISSUE THREAD

**Issue by SamHaoYuan** [guyulongcs/WSDM2020_HUP#2]
作者您好，最近在重现您工作的时候，对于模型HUB模型第一层的输入有一些困惑，想要请教一下；
我看到您论文中描述，第一层的behavior gate是使用的是micro-behaviors的信息，那么这一层的input,即x使用的是哪一个embedding？也是behaviors吗？

**Comment by guyulongcs** [comment]
你好！x应该是各种embedding的拼接，具体可以看下我们的代码。

*Have a nice day!*

*Yulong Gu** [**谷育龙**]*

*Email: **guyulongcs@gmail.com <guyulongcs@gmail.com>*

**Comment by SamHaoYuan** [comment]
感谢您的回复，我正在尝试阅读代码，只是在结合论文阅读过程中有一些困惑；

模型第一层的x是全部embedding的拼接，那么就相当于后续两层（item与category）就是在上一层输出的基础之上，重复拼接了item embedding 与 category 信息吗？

再次感谢~

**Comment by guyulongcs** [comment]
是的。

*Have a nice day!*

*Yulong Gu*

*Email: **guyulongcs@gmail.com <guyulongcs@gmail.com>*
